name: 🛠️ CI

on:
  pull_request:
  push:
    branches: [main]

  workflow_call:

env:
  RUSTFLAGS: "-Dwarnings"

jobs:
  lint:
    name: 📝 Lint Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: 📦 Install Rustfmt
        run: rustup component add rustfmt

      - name: 🦀 Run Rustfmt
        run: cargo fmt --all -- --check

  clippy:
    name: 🔍 Lint Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - name: 🦀 Run Clippy
        run: cargo clippy --workspace --all-targets --all-features --locked -- -D warnings

  shear:
    name: ✂️ Check Code Shearing (unwanted package dependencies)
    runs-on: ubuntu-latest
    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v5

      - name: 📦 Install cargo-binstall
        uses: cargo-bins/cargo-binstall@main

      - name: ✂️ Install cargo-shear
        run: cargo binstall --no-confirm cargo-shear

      - name: 🔍 Run cargo shear
        run: cargo shear

  test:
    name: 🚀 Run Test Suite
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: 📦 Checkout Repository
        uses: actions/checkout@v5

      - name: 🦀 Setup Rust (stable)
        uses: dtolnay/rust-toolchain@stable

      - name: 📂 Cache Cargo
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: 📦 Install cargo-llvm-cov
        run: cargo install cargo-llvm-cov

      - name: 🧪 Run tests + collect coverage
        run: cargo llvm-cov --workspace --all-features --lcov --output-path lcov.info

      - name: ☁️ Upload to Codecov
        uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          fail_ci_if_error: true
